### PR TITLE
Update tfml.txt

### PR DESCRIPTION
**Pull request by Walkman100**
fix line breaks

### CODE REVIEW

**Comment by Walkman100** [comment]
@deavmi go to the bottom of https://raw.githubusercontent.com/FreeMusicFederation/license/master/tfml.txt
I'm sure it's not supposed to look like that

**Comment by Walkman100** [comment]
image

**Comment by deavmi** [comment]
Waiting for a reply on another PR by @iamale, whereby this problem no longer exists and no longer needs a PR.

**Comment by Walkman100** [comment]
Oh. okay then

**Comment by deavmi** [comment]
@Walkman100 Thanks anyway tho bro ;D :wink:

**Pull request closed without merging**
