### PR TITLE
Formatting, FDL

### PR DESCRIPTION
**Pull request by iamale**
For FDL I used the wording from https://gnu.org/licenses/fdl-howto-opt.html

### CODE REVIEW

**Comment by deavmi** [comment]
Fdl

**Comment by deavmi** [comment]
Oh so. You basically just changed the formatting and wording. But not the meaning? Right. :D @iamale

**Comment by iamale** [comment]
Yeah. I think we should stick with Markdown for now, as it is rendered automatically (and easier to read this way). I didn't make any changes to the body apart from that.

I've changed the FDL header text so it more resembles the official one, though.

**Comment by deavmi** [comment]
@iamale The heading being? The way you state how something is licensed?

**Comment by iamale** [comment]
Yeah. I think we should stick with Markdown for now, as it is rendered automatically (and easier to read this way). I didn't make any changes to the body apart from that.

I've changed the FDL header text so it more resembles the official one, though.

**Comment by deavmi** [comment]
@iamale Thanks. Merged :wink:

**Pull request merged**
